TECH_SKILLS = {
    # Programming languages
    "python": ["python", "py", "python3"],
    "java": ["java", "jdk", "jvm"],
    "javascript": ["javascript", "js", "ecmascript", "es6"],
    "typescript": ["typescript", "ts"],
    "c++": ["c++", "cpp", "cplusplus"],
    "c#": ["c#", "csharp", "dotnet", ".net"],
    "php": ["php"],
    "ruby": ["ruby", "ruby on rails", "rails"],
    "swift": ["swift", "swiftui"],
    "kotlin": ["kotlin"],
    "go": ["golang", "go"],
    "rust": ["rust"],
    "scala": ["scala"],
    "r": ["rstats", "r programming"],
    "perl": ["perl"],
    "haskell": ["haskell"],
    "bash": ["bash", "shell scripting", "shell"],
    "powershell": ["powershell"],

    # Web/Frontend
    "html": ["html", "html5"],
    "css": ["css", "css3", "scss", "sass"],
    "react": ["react", "reactjs", "react.js"],
    "angular": ["angular", "angularjs", "angular.js"],
    "vue": ["vue", "vuejs", "vue.js"],
    "jquery": ["jquery"],
    "bootstrap": ["bootstrap"],
    "tailwind": ["tailwindcss", "tailwind"],
    "redux": ["redux"],
    "gatsby": ["gatsby", "gatsbyjs"],
    "next.js": ["next.js", "nextjs"],
    "svelte": ["svelte"],
    "graphql": ["graphql"],
    "webpack": ["webpack"],
    "babel": ["babel"],

    # Backend Frameworks
    "django": ["django"],
    "flask": ["flask"],
    "fastapi": ["fastapi"],
    "spring": ["spring", "spring boot"],
    "laravel": ["laravel"],
    "symfony": ["symfony"],
    "express": ["express", "expressjs", "express.js"],
    "node.js": ["node.js", "nodejs", "node"],
    "asp.net": ["asp.net"],
    "phoenix": ["phoenix framework", "phoenix"],
    
    # Databases
    "sql": ["sql"],
    "mysql": ["mysql"],
    "postgresql": ["postgresql", "postgres"],
    "mongodb": ["mongodb", "mongo"],
    "sqlite": ["sqlite"],
    "oracle": ["oracle", "oracle db"],
    "redis": ["redis"],
    "dynamodb": ["dynamodb"],
    "firebase": ["firebase"],
    "cassandra": ["cassandra"],
    "elasticsearch": ["elasticsearch", "elastic"],
    "neo4j": ["neo4j"],
    "graphdb": ["graphdb"],
    
    # Cloud/DevOps
    "aws": ["aws", "amazon web services", "ec2", "s3", "lambda"],
    "azure": ["azure", "microsoft azure"],
    "gcp": ["gcp", "google cloud", "google cloud platform"],
    "docker": ["docker", "dockerfile", "docker-compose"],
    "kubernetes": ["kubernetes", "k8s"],
    "terraform": ["terraform"],
    "jenkins": ["jenkins"],
    "github actions": ["github actions", "github workflow"],
    "gitlab ci": ["gitlab ci", "gitlab pipeline"],
    "circleci": ["circleci"],
    "ansible": ["ansible"],
    "chef": ["chef"],
    "puppet": ["puppet"],
    
    # AI/ML/Data Science
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning", "dl"],
    "ai": ["artificial intelligence", "ai"],
    "tensorflow": ["tensorflow", "tf"],
    "pytorch": ["pytorch", "torch"],
    "keras": ["keras"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "pandas": ["pandas"],
    "numpy": ["numpy", "np"],
    "scipy": ["scipy"],
    "matplotlib": ["matplotlib"],
    "nlp": ["nlp", "natural language processing"],
    "computer vision": ["computer vision", "cv", "opencv"],
    "data mining": ["data mining"],
    "neural networks": ["neural networks", "neural nets", "ann", "cnn", "rnn", "lstm"],
    "transformers": ["transformers", "bert", "gpt", "huggingface"],
    "data science": ["data science"],
    "eda": ["exploratory data analysis", "eda"],
    
    # Mobile
    "android": ["android", "android studio"],
    "ios": ["ios", "iphone development"],
    "flutter": ["flutter"],
    "react native": ["react native"],
    "xamarin": ["xamarin"],
    "cordova": ["cordova", "phonegap"],
    
    # Version Control
    "git": ["git", "github", "gitlab", "bitbucket"],
    "svn": ["svn", "subversion"],
    "mercurial": ["mercurial", "hg"],
    
    # Testing
    "junit": ["junit"],
    "pytest": ["pytest"],
    "jest": ["jest"],
    "selenium": ["selenium"],
    "cypress": ["cypress"],
    "mocha": ["mocha"],
    "chai": ["chai"],
    "jasmine": ["jasmine"],
    
    # Other
    "restful api": ["rest", "restful", "restapi", "rest api"],
    "soap": ["soap api", "soap"],
    "graphql": ["graphql"],
    "json": ["json"],
    "xml": ["xml"],
    "iot": ["iot", "internet of things"],
    "blockchain": ["blockchain", "ethereum", "hyperledger", "smart contracts"],
    "microservices": ["microservices", "microservice architecture"],
    "serverless": ["serverless", "faas"],
    "agile": ["agile", "scrum", "kanban"],
    "jira": ["jira", "atlassian"],
    "devops": ["devops"],
    "cicd": ["ci/cd", "cicd", "continuous integration", "continuous deployment"],
    "websockets": ["websockets", "socket.io"],
    "pwa": ["pwa", "progressive web app"],
    "responsive design": ["responsive design", "responsive"],
    "ui/ux": ["ui/ux", "user interface", "user experience"],
    "figma": ["figma"],
    "cybersecurity": ["cybersecurity", "infosec", "security"],
    "blockchain": ["blockchain", "cryptocurrency", "crypto", "bitcoin", "ethereum", "solidity"],
    "big data": ["big data", "hadoop", "spark"],
    "ar/vr": ["augmented reality", "virtual reality", "ar", "vr"],
}